jobapp/urls.py
from django.urls import path
from .views import *
from .import views

app_name = 'jobapp'
urlpatterns = [
     # jobseekers
    path('', JobseekerHomeView.as_view(), name='jobseekerhome'),
    path('jobseeker/registration/',
         JobSeekerRegistrationView.as_view(), name='jobseekerregistration'),
    path('login/', JobSeekerLoginView.as_view(), name='jobseekerlogin'),
    path('job/<int:pk>/detail/',
         JobDetailView.as_view(), name='jobdetails'),
    path('job/<int:pk>/apply/', JobSeekerJobApplyView.as_view(),
         name='jobseekerjobapply'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),
    path('jobseeker/cv_builder', CVBuilderView.as_view(), name="cv_builder"),

    #employer
    path('employer/registration', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('employer/home/', EmployerHomeView.as_view(), name='employerhome'),
    path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
    path('jobseeker/profile/<int:pk>/update/',
         JobseekerProfileUpdateView.as_view(), name='jobseekerprofileupdate'),
    path('employer/profile/', EmployerProfileView.as_view(), name='employerprofile'),
    path('employer/job/<int:pk>/detail/',
         EmployerJobDetailView.as_view(), name='employerjobdetail'),
    path('employer/job/post/', EmployerJobCreateView.as_view(),
         name='employerjobcreate'),
    path('employer/profile/<int:pk>/update/',
         EmployerProfileUpdateView.as_view(), name='employerprofileupdate'),
    path('employer/job/<int:pk>/update/',
         EmployerJobUpdateView.as_view(), name='employerjobupdate'),
    path('employer/job/<int:pk>/delete/',EmployerJobDeleteView.as_view(),name='employerjobdelete'),

         #admin
    path('job-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('admin/employer/list/', AdminEmployerListView.as_view(),
         name='adminemployerlist'),
   path('admin/employer/<int:pk>/delete/',AdminEmployerDeleteView.as_view(),name='adminemployerdelete'),
    path('admin/employer/<int:pk>/detail/',
         AdminEmployerDetailView.as_view(), name='adminemployerdetail'),
    path('admin/jobseeker/list/', AdminJobseekerListView.as_view(),
         name='adminjobseekerlist'),
    path('admin/jobseeker/<int:pk>/detail/',
         AdminJobSeekerDetailView.as_view(), name='adminjobseekerdetail'),
    path('admin/jobseeker/<int:pk>/delete/',AdminJobseekerDeleteView.as_view(),name='adminjobseekerdelete'),
   
    path('admin/job/list/', AdminJobListView.as_view(), name='adminjoblist'),
    path('admin/job/<int:pk>/detail/',
         AdminJobDetailView.as_view(), name='adminjobdetail'),

    path('admin/job/status/<int:pk>/change',
         AdminJobStatusChange.as_view(), name='adminjobstatuschange'),

    path('logout/', LogoutView.as_view(), name='logout'), 

    #for all
    path('search/', SearchView.as_view(), name='search'),
    path('alljob/', JobView.as_view(), name='alljob'),
    path('allcompany/', CompanyView.as_view(), name='allcompany'),
    path('generate/pdf/',views.generate_pdf,name='generate_pdf'),
    path('admin/search/',AdminSearchView.as_view(),name='adminsearch'),
    
]

jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf  import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls'))
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/employertemplates/employerbase.html
<html>
{% load static %}

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'jobseekerstatic/css/style.css' %} ">
    <link rel="stylesheet" href="{% static 'jobseekerstatic/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jobseekerstatic/css/fontawesome.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    {% block css %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'jobapp:jobseekerhome' %}"><strong>JOB PORTAL</strong> </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <div class="mr-auto"></div>

            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'jobapp:jobseekerhome' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>

                <!-- <li class="nav-item">
                    <a class="nav-link text-dark" href="">Jobs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="">Company</a>
                </li> -->

                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-dark"
                        href="{% url 'jobapp:employerprofile' %}">My Profile</a>
				</li>
				<li class="nav-item">
                    <a class="nav-link text-dark"
                        href="{% url 'jobapp:employerjobcreate' %}">Create Job</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'jobapp:logout'%}?next={{request.path}}">Logout</a>
                </li>
                {% else %}
				<li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Register
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'jobapp:jobseekerregistration' %}">Job Seeker</a>
                        <a class="dropdown-item" href="{% url 'jobapp:employerregistration' %}">Employer</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'jobapp:jobseekerlogin' %}?next={{request.path}}">Login</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
   

    <script src="{% static 'jobseekerstatic/js/popper.min.js' %}"></script>
    <script src="{% static 'jobseekerstatic/js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'jobseekerstatic/js/bootstrap.min.js' %}"></script>

    {% block js %}
    {% endblock %}
</body>

</html>

templates/employertemplates/employerhome.html
{% extends 'employertemplates/employerbase.html' %}
{% block title %}Job Portal{% endblock %}
{% block content %}

{% endblock %}

templates/employertemplates/employerjobcreate.html
{% extends 'employertemplates/employerbase.html' %}
{% block title %}Create Job{% endblock %}
{% block content %}
<div class="container border">
	<h3 style="margin-left: 31%;">Create New Job</h3>

	<form method="post" enctype="multipart/form-data" style="margin-left: 30%;">
		{% csrf_token %}
		{% for field in form %}
		<div class="form-group col-md-8">
			
			<label for="{{ field.id_for_label}}" class="label">{{ field.label }} </label>
			
			{{ field }}
		</div>
		{% if field.errors %}
		<li class="alert alert-warning alert-dismissible fade show" role="alert">
			<strong>{{field.label}}</strong>&nbsp;{{field.errors|striptags}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button></li>
		{% endif %}
		{% endfor %}
		<button class="btn btn-success">Create Job</button>

	</form>
</div>
{% endblock %}

templates/employertemplates/employerjobdelete.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<div class="container">
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
    <a href="{% url 'jobapp:employerprofile' %}">Cancel</a>
</form>
</div>
{% endblock %}

templates/employertemplates/employerjobdetail.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<div class="container">
	<h3>Job Details</h3>
	<p><strong>Title: </strong>{{jobobject.title}} </p>
	<p><strong>Job Level: </strong>{{jobobject.level}} </p>
	<p><strong>Experience: </strong>{{jobobject.experience}} </p>
	<p><strong>Salary: </strong>{{jobobject.salary}} </p>
	<p><strong>Skills: </strong>{{jobobject.skills}} </p>
	<p><strong>Created On: </strong>{{jobobject.created_at}} </p>
	<p><strong>Category: </strong>{{jobobject.category}} </p>
	<p><strong>Deadline: </strong>{{jobobject.deadline}} </p>
	<p><strong>No. of Vaccancies: </strong>{{jobobject.vaccncy_number}} </p>
	<p><strong>Details: </strong>{{jobobject.details}} </p>
	<button class=" btn btn-success"><a
		href="{% url 'jobapp:employerjobupdate' jobobject.id %}">Update</a></button>
	<br><br>
	<h3>Job Application for this job</h3>
	<table class='table'>
		<thead>
			<tr>
				<th>SN</th>
				<th>Applicant</th>
				<th>Applied on</th>
				<th>Documents submitted</th>
			<tr>
		</thead>
		<tbody>
			{% for application in jobobject.jobapplication_set.all %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{application.jobseeker.name}}</td>
				<td>{{application.created_at}}</td>
				<td>
					<button class="btn btn-warning"> <a href="{{application.jobseeker.cv.url}}" download>Download
							Cv</a></button>
					<button class="btn btn-warning"><a href="{{application.cover_letter.url}}" download>Download
							coverletter</a></button>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

templates/employertemplates/employerjobupdate.html
{% extends 'employertemplates/employerbase.html' %}
{% block title %}Update Job{% endblock %}
{% block content %}
<div class="container">
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% for field in form %}
		<div class="form-group col-md-8">
			<label for="{{ field.id_for_label}}" class="label">{{ field.label }}</label>
			{{ field }}
		</div>
		{% if field.errors %}
		<li class="alert alert-warning alert-dismissible fade show" role="alert">
			<strong>{{field.label}}</strong>&nbsp;{{field.errors|striptags}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button></li>
		{% endif %}
		{% endfor %}
		<button class="btn btn-primary">Update</button>
	</form>
</div>
{% endblock %}

templates/employertemplates/employerprofile.html
{% extends 'employertemplates/employerbase.html' %}
{% block title %}My Profile{% endblock %}
{% block content %}
<br>
<div class="container mx-auto">
	<div class="row">
		<div class="col-md-4">
			
			<img src="{{employer.company_image.url}}" alt="" class="img-fluid">
			
		</div>	
		<div class="col-md-8">
			<p><strong>Name: </strong>{{employer.name}} </p>
			<p><strong>Email: </strong>{{employer.email}} </p>
			<p><strong>Address: </strong>{{employer.address}} </p>
			<p><strong>Contact: </strong>{{employer.mobile}} </p>
			<p><strong>Website: </strong>{{employer.website}} </p>
			<hr>
			<button class="btn btn-warning"><a
					href="{% url 'jobapp:employerprofileupdate' employer.id %}">Update Profile</a></button>
		</div>
	</div>
	<br>
	<table class='table'>
		<thead>
			<tr>
				<th>Sn</th>
				<th>Job title</th>
				<th>Deadline</th>
				<th>Posted on</th>
				<th>Status</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			{% for job in employer.job_set.all %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td><a
						href="{% url 'jobapp:employerjobdetail' job.id %}">{{job.title}}({{job.jobapplication_set.count}}application)</a>
				</td>
				<td>{{job.deadline}}</td>
				<td>{{job.created_at}}</td>
				<td>{{job.status}}</td>
				<td>
					<a type="button" class="btn btn-warning" href="{% url 'jobapp:employerjobupdate' job.id %}">Update</a>
					<a  type ="button" class="btn btn-danger" href="{% url 'jobapp:employerjobdelete' job.id %}">Delete</a>

				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

{% endblock %}

templates/employertemplates/employerprofileupdate.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<div class="container">
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% for field in form %}
		<div class="form-group col-md-8">
			<label for="{{ field.id_for_label}}" class="label">{{ field.label }}</label>
			{{ field }}
		</div>
		{% if field.errors %}
		<li class="alert alert-warning alert-dismissible fade show" role="alert">
			<strong>{{field.label}}</strong>&nbsp;{{field.errors|striptags}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button></li>
		{% endif %}
		{% endfor %}
		<button class="btn btn-primary">Update</button>
	</form>
</div>
{% endblock %}

templates/employertemplates/employerregistration.html
{% extends 'employertemplates/employerbase.html' %}
{% block content %}
<div class="container border">
	<h3 style="margin-left: 30%;">Registration Page for Employer</h3>
	<form method="post" enctype="multipart/form-data" style="margin-left: 30%;">
		{% csrf_token %}
		{% for field in form %}
		<div class="form-group col-md-8">
			<label for="{{ field.id_for_label}}" class="label">{{ field.label }}</label>
			{{ field }}
		</div>
		{% if field.errors %}
		<li class="alert alert-warning alert-dismissible fade show" role="alert">
			<strong>{{field.label}}</strong>&nbsp;{{field.errors|striptags}}
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button></li>
		{% endif %}
		{% endfor %}
		<button type="submit" class="btn btn-primary">Register</button>
	</form>

	<div class="d-flex justify-content-center links">
		Already have an account? <a href="{% url 'jobapp:jobseekerlogin' %}" class="ml-2">Sign In</a>
	</div>
</div>
{% endblock %}