jobapp/urls.py
from django.urls import path
from .views import *
from .import views

app_name = 'jobapp'
urlpatterns = [
     # jobseekers
    path('', JobseekerHomeView.as_view(), name='jobseekerhome'),
    path('jobseeker/registration/',
         JobSeekerRegistrationView.as_view(), name='jobseekerregistration'),
    path('login/', JobSeekerLoginView.as_view(), name='jobseekerlogin'),
    path('job/<int:pk>/detail/',
         JobDetailView.as_view(), name='jobdetails'),
    path('job/<int:pk>/apply/', JobSeekerJobApplyView.as_view(),
         name='jobseekerjobapply'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),
    path('jobseeker/cv_builder', CVBuilderView.as_view(), name="cv_builder"),

    #employer
    path('employer/registration', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('employer/home/', EmployerHomeView.as_view(), name='employerhome'),
    path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
    path('jobseeker/profile/<int:pk>/update/',
         JobseekerProfileUpdateView.as_view(), name='jobseekerprofileupdate'),
    path('employer/profile/', EmployerProfileView.as_view(), name='employerprofile'),
    path('employer/job/<int:pk>/detail/',
         EmployerJobDetailView.as_view(), name='employerjobdetail'),
    path('employer/job/post/', EmployerJobCreateView.as_view(),
         name='employerjobcreate'),
    path('employer/profile/<int:pk>/update/',
         EmployerProfileUpdateView.as_view(), name='employerprofileupdate'),
    path('employer/job/<int:pk>/update/',
         EmployerJobUpdateView.as_view(), name='employerjobupdate'),
    path('employer/job/<int:pk>/delete/',EmployerJobDeleteView.as_view(),name='employerjobdelete'),

         #admin
    path('job-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('admin/employer/list/', AdminEmployerListView.as_view(),
         name='adminemployerlist'),
   path('admin/employer/<int:pk>/delete/',AdminEmployerDeleteView.as_view(),name='adminemployerdelete'),
    path('admin/employer/<int:pk>/detail/',
         AdminEmployerDetailView.as_view(), name='adminemployerdetail'),
    path('admin/jobseeker/list/', AdminJobseekerListView.as_view(),
         name='adminjobseekerlist'),
    path('admin/jobseeker/<int:pk>/detail/',
         AdminJobSeekerDetailView.as_view(), name='adminjobseekerdetail'),
    path('admin/jobseeker/<int:pk>/delete/',AdminJobseekerDeleteView.as_view(),name='adminjobseekerdelete'),
   
    path('admin/job/list/', AdminJobListView.as_view(), name='adminjoblist'),
    path('admin/job/<int:pk>/detail/',
         AdminJobDetailView.as_view(), name='adminjobdetail'),

    path('admin/job/status/<int:pk>/change',
         AdminJobStatusChange.as_view(), name='adminjobstatuschange'),

    path('logout/', LogoutView.as_view(), name='logout'), 

    #for all
    path('search/', SearchView.as_view(), name='search'),
    path('alljob/', JobView.as_view(), name='alljob'),
    path('allcompany/', CompanyView.as_view(), name='allcompany'),
    path('generate/pdf/',views.generate_pdf,name='generate_pdf'),
    path('admin/search/',AdminSearchView.as_view(),name='adminsearch'),
    
]

jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf  import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls'))
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminbase.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<title></title>
	<link rel="stylesheet" type="text/css" href="{% static 'jobseekerstatic/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'adminstatic/style.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% block css %}

	{% endblock %}
</head>
<body>

<div class="sidenav">
  <a href="{% url 'jobapp:adminhome' %}">Dashboard</a>
  <a href="{% url 'jobapp:adminemployerlist' %}">Employer</a>
  <a href="{% url 'jobapp:adminjobseekerlist' %}">Jobseeker</a>
  <a href="{% url 'jobapp:adminjoblist' %}">Jobs</a>
  <!-- <a href="#contact">Contact</a>
  <a href="#contact">Search</a> -->
</div>

	

{% block content %}
{% endblock %}

<script
  src="https://code.jquery.com/jquery-3.4.0.min.js"
  integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
  crossorigin="anonymous"></script>
{% block js %}
{% endblock  %}


</body>
</html>

templates/admintemplates/adminemployerdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<div class="main">
<h1>AdminEmployerDetail</h1>
<table class="table table-dark">
	<thead>
		<tr>
			<th>Name</th>
			<th>Address</th>
			<th> mobile</th>
			<th>Email</th>
			<th>address</th>
			<th>image</th>
			<th>Website</th>

		</tr>	

	</thead>
	<tbody>
		<tr>
			<td>{{adminemployerobject.name}}</td>
			<td>{{adminemployerobject.address}}</td>
			<td>{{adminemployerobject.mobile}}</td>
			<td>{{adminemployerobject.email}}</td>
			<td>{{adminemployerobject.address}}</td>
			<td><img src="{{adminemployerobject.company_image.url}}"></td>
			<td>{{adminemployerobject.website}}</td>
		</tr>
	</tbody>
	

</table>
</div>
{% endblock %}

templates/admintemplates/adminemployerlist.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<div class="main">

<h1>Employer list</h1>
<table class="table table-dark">
	<thead>
		<tr>
			<th>Sn</th>
			<th>Employer Name</th>
			<th>Employer mobile</th>
			<th>Employer Email</th>
			<th>Employer Address</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		{% for employer in adminemployer %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{employer.name}}</td>
				<td>{{employer.mobile}}</td>
				<td>{{employer.email}}</td>
				<td>{{employer.address}}</td>
				<td><a href="{% url 'jobapp:adminemployerdetail' employer.id %}">Detail</a>|
					<a href="{% url 'jobapp:adminemployerdelete' employer.id %}">Delete</a>
	
				</td>

			
		</tr>
		{% endfor %}
	</tbody>
</table>
</div>


{% endblock %}

templates/admintemplates/adminhome.html
{% extends 'admintemplates/adminbase.html' %}
{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css">

{% endblock %}
{% block content %}

<div class="main">
    <br>
    <form method='GET' action="{% url 'jobapp:adminsearch' %}">
        <input type="text" name="q" placeholder="Jobseeker Name,Company Name"/ class="form-control">
        <!-- <input type="submit"  value="Search"/> -->
        <hr>
        <button class="btn btn-primary" type="submit">Search</button>
      </form>
      <br>
<div class="row">
	<div class="col-md-3 bg-success p-3">
		<h3 class="text-center text-white">{{allemployers.count}}</h3>
		<h4 class="text-center">Employers</h4>
	</div>
	<div class="col-md-3 bg-warning p-3">
		<h3 class="text-center text-white">{{alljobs.count}}</h3>
		<h4 class="text-center">Jobs</h4>

	</div>
	<div class="col-md-3 bg-info p-3">
		<h3 class="text-center text-white">{{alljobseekers.count}}</h3>
		<h4 class="text-center">Jobseeker</h4>

	</div>
	<div class="col-md-3 bg-danger p-3">
		<h3 class="text-center text-white">{{allapplications.count}}</h3>
		<h4 class="text-center">JobApplication</h4>
	</div>
</div>
	<div class="row">
		<div class="col-md-6">
            <h3>Employers Statistics</h3></hr>
			<canvas id="myChart" width="400" height="400"></canvas>
		</div>
        <div class="col-md-6">
            <h3>Job Statistics</h3></hr>
            <canvas id="jobChart" width="400" height="400"></canvas>
        </div>
    </div>
</div>


{% endblock %}
{% block js %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
<script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'pie',
    data: {
        labels: [{% for employer in allemployers %}"{{employer.name}}",{% endfor %}],
        datasets: [{
            label: '# Job Statistic',
            data: [{% for employer in allemployers %}"{{employer.job_set.all.count}}",{% endfor %}],
            backgroundColor: [
            '#799746',
                // 'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
               
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
var job = document.getElementById('jobChart');
var jobChart = new Chart(job, {
    type: 'bar',
    data: {
        labels: [{% for job in alljobs %}"{{job.title}}",{% endfor %}],
        datasets: [{
            label: '# Job Statistic',
            data: [{% for job in alljobs %}"{{job.jobapplication_set.all.count}}",{% endfor %}],
            backgroundColor: [
            '#799746',
                // 'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
               
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});


var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
  dropdown[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var dropdownContent = this.nextElementSibling;
    if (dropdownContent.style.display === "block") {
      dropdownContent.style.display = "none";
    } else {
      dropdownContent.style.display = "block";
    }
  });
}
</script>
{% endblock %}  

templates/admintemplates/adminjobdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<div class="main">
<h1>JobDetail</h1>
<table class="table table-info">
	<thead>
		<tr>
			<th>Title</th>
			<th>Image</th>
			<th>Type</th>
			<th>Level</th>
			<th>Cateogry</th>
			<th>Company</th>
			<th>deadline</th>
			<th>vaccency</th>
			<th>education</th>
			<th>skills</th>
			<th>details</th>
			<th>experience</th>
			<th>salary</th>
			<th>Status</th>
		</tr>

	</thead>
	<tbody>
	<td>{{jobdetailobject.title}}</td>
	<td><img src="{{jobdetailobject.image.url}}" width="200"></td>
	<td>{{jobdetailobject.job_type}}</td>
	<td>{{jobdetailobject.level}}</td>
	<td>{{jobdetailobject.category}}</td>
	<td>{{jobdetailobject.employer}}</td>
	<td>{{jobdetailobject.deadline}}</td>
	<td>{{jobdetailobject.vaccncy_number}}</td>
	<td>{{jobdetailobject.education}}</td>
	<td>{{jobdetailobject.skills}}</td>
	<td>{{jobdetailobject.details}}</td>
	<td>{{jobdetailobject.experience}}</td>
	<td>{{jobdetailobject.salary}}</td>
	<td>{{jobdetailobject.status}}</td>


	</tbody>
	
</table>
</div>
{% endblock %}

templates/admintemplates/adminjoblist.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<div class="main">
<h1>JobList</h1>
<table class="table">
	<thead>
		<tr>
			<th>Sn</th>
			<th>JobTitle</th>
			<th>Image</th>
			<th>Status</th>
		
		</tr>

		

	</thead>
	<tbody>
		{% for job in jobobject %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td><a href="{% url 'jobapp:adminjobdetail' job.id %}">{{job.title}}</td>
			<td><img src="{{job.image.url}}" width="200"></td>
			<td>{% if not job.status == 'completed' %}<a href="{% url 'jobapp:adminjobstatuschange' job.id %}">{{job.status}} {% else %}<button type="button" class="btn btn-success">Completed</button>{% endif %}</a></td>
			
		</tr>
		{% endfor %}
	</tbody>
	

</table>
</div>

{% endblock %}

templates/admintemplates/adminjobseekerdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<div class="main">
<h1>JobSeekeerDetailView</h1>
<table class="table table-info">
	<thead>
		<tr>
			<th>Name</th>
			<th>Address</th>
			<th>Mobile</th>
			<th>Email</th>
			<th>Skills</th>
			<th>qualification</th>
			<th>about</th>
			<th>Image</th>
		
		</tr>
	</thead>
	<tbody>
		<td>{{jobseekerdetailobject.name}}</td>
		<td>{{jobseekerdetailobject.address}}</td>
		<td>{{jobseekerdetailobject.mobile}}</td>
		<td>{{jobseekerdetailobject.email}}</td>
		<td>{{jobseekerdetailobject.skills}}</td>
		<td>{{jobseekerdetailobject.qualification}}</td>
		<td>{{jobseekerdetailobject.about}}</td>
		<td><img src="{{jobseekerdetailobject.image.url}}"></td>

	</tbody>
	
</table>
</div>
{% endblock %}

templates/admintemplates/adminjobseekerlist.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<div class="main">

<h1>JobSeekerList</h1>

<table class="table table-dark">
	<thead>
		<tr>
			<th>Sn</th>
			<th>name</th>
			<th>address</th>
			<th>mobile</th>
			<th>Action</th>
			
		</tr>
	</thead>
	<tbody>
		{% for jobseeker in jobseekerobject %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{jobseeker.name}}</td>
			<td>{{jobseeker.address}}</td>
			<td>{{jobseeker.mobile}}</td>
			<td><a href="{% url 'jobapp:adminjobseekerdelete' jobseeker.id %}">Delete</a>|
			<a href="{% url 'jobapp:adminjobseekerdetail' jobseeker.id %}">Detail</td>
			

		</tr>
		{% endfor %}
	</tbody>

	

</table>
</div>

{% endblock %}

templates/admintemplates/adminjobstatuschange.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<div class="main">
<form method="post">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-primary">Change Status</button>
</form>
</div>
{% endblock %}

templates/admintemplates/delete.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<div class="main">
<div class="container">
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object.name}}"?</p>
        <input type="submit" value="Confirm" />
        <a href="{% url 'jobapp:adminjobseekerlist' %}">Cancel</a>
    </form>
    </div>
    </div>

{% endblock %}

templates/admintemplates/employerdelete.html
{% extends 'admintemplates/adminbase.html' %}
{% block content %}
<div class="main">
<div class="container">
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
        <a href="{% url 'jobapp:adminemployerlist' %}">Cancel</a>
    </form>
    </div>
    </div>

{% endblock %}

templates/admintemplates/login.html
{% block content %}
<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>


<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% if error %}
	<li style="color:red">{{error}}</li>
	{% endif %}
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>


{% endblock %}

templates/admintemplates/search.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<div class="main">
{% if results %}

<table class="table table-dark">
    <thead>
      <tr>
         <th>Sn</th>
        <th>Name</th>
        <th>email</th>
        <th>Address</th>
     
      </tr>
    </thead>
    <tbody>
        {% for result in results %}
      <tr>
          <td>{{forloop.counter}}</td>
          {% if result.skills %}
          <td><a href="{% url 'jobapp:adminjobseekerdetail' result.id %}">{{result.name}}</a></td>
        {% else %}
        <td><a href="{% url 'jobapp:adminemployerdetail' result.id %}">{{result.name}}</a></td>
        {% endif %}
        <td>{{result.email}}</td> 
        <td>{{result.address}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}

</div>
{% endblock %}