jobapp/urls.py
from django.urls import path
from .views import *
from .import views

app_name = 'jobapp'
urlpatterns = [
     # jobseekers
    path('', JobseekerHomeView.as_view(), name='jobseekerhome'),
    path('jobseeker/registration/',
         JobSeekerRegistrationView.as_view(), name='jobseekerregistration'),
    path('login/', JobSeekerLoginView.as_view(), name='jobseekerlogin'),
    path('job/<int:pk>/detail/',
         JobDetailView.as_view(), name='jobdetails'),
    path('job/<int:pk>/apply/', JobSeekerJobApplyView.as_view(),
         name='jobseekerjobapply'),
    path('jobseeker/profile/', JobSeekerProfileView.as_view(),
         name='jobseekerprofile'),
    path('jobseeker/cv_builder', CVBuilderView.as_view(), name="cv_builder"),

    #employer
    path('employer/registration', EmployerRegistrationView.as_view(),
         name='employerregistration'),
    path('employer/home/', EmployerHomeView.as_view(), name='employerhome'),
    path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
    path('jobseeker/profile/<int:pk>/update/',
         JobseekerProfileUpdateView.as_view(), name='jobseekerprofileupdate'),
    path('employer/profile/', EmployerProfileView.as_view(), name='employerprofile'),
    path('employer/job/<int:pk>/detail/',
         EmployerJobDetailView.as_view(), name='employerjobdetail'),
    path('employer/job/post/', EmployerJobCreateView.as_view(),
         name='employerjobcreate'),
    path('employer/profile/<int:pk>/update/',
         EmployerProfileUpdateView.as_view(), name='employerprofileupdate'),
    path('employer/job/<int:pk>/update/',
         EmployerJobUpdateView.as_view(), name='employerjobupdate'),
    path('employer/job/<int:pk>/delete/',EmployerJobDeleteView.as_view(),name='employerjobdelete'),

         #admin
    path('job-admin/', AdminHomeView.as_view(), name='adminhome'),
    path('admin/employer/list/', AdminEmployerListView.as_view(),
         name='adminemployerlist'),
   path('admin/employer/<int:pk>/delete/',AdminEmployerDeleteView.as_view(),name='adminemployerdelete'),
    path('admin/employer/<int:pk>/detail/',
         AdminEmployerDetailView.as_view(), name='adminemployerdetail'),
    path('admin/jobseeker/list/', AdminJobseekerListView.as_view(),
         name='adminjobseekerlist'),
    path('admin/jobseeker/<int:pk>/detail/',
         AdminJobSeekerDetailView.as_view(), name='adminjobseekerdetail'),
    path('admin/jobseeker/<int:pk>/delete/',AdminJobseekerDeleteView.as_view(),name='adminjobseekerdelete'),
   
    path('admin/job/list/', AdminJobListView.as_view(), name='adminjoblist'),
    path('admin/job/<int:pk>/detail/',
         AdminJobDetailView.as_view(), name='adminjobdetail'),

    path('admin/job/status/<int:pk>/change',
         AdminJobStatusChange.as_view(), name='adminjobstatuschange'),

    path('logout/', LogoutView.as_view(), name='logout'), 

    #for all
    path('search/', SearchView.as_view(), name='search'),
    path('alljob/', JobView.as_view(), name='alljob'),
    path('allcompany/', CompanyView.as_view(), name='allcompany'),
    path('generate/pdf/',views.generate_pdf,name='generate_pdf'),
    path('admin/search/',AdminSearchView.as_view(),name='adminsearch'),
    
]

jobproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf  import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('jobapp.urls'))
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/jobseekertemplates/base.html
<html>
{% load static %}

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'jobseekerstatic/css/style.css' %} ">
    <link rel="stylesheet" href="{% static 'jobseekerstatic/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jobseekerstatic/css/fontawesome.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
        integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    {% block css %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'jobapp:jobseekerhome' %}"><strong>JOB PORTAL</strong> </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <div class="mr-auto"></div>

            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'jobapp:jobseekerhome' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'jobapp:alljob' %}">Jobs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'jobapp:allcompany' %}">Company</a>
                </li>

                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'jobapp:jobseekerprofile' %}">My Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'jobapp:logout'%}?next={{request.path}}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Register
                    </a>
                    <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown"> -->
                        <a class="dropdown-item" href="{% url 'jobapp:jobseekerregistration' %}">Job Seeker</a>
                        <a class="dropdown-item" href="{% url 'jobapp:employerregistration' %}">Employer</a>
                    <!-- </div> -->
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark"
                        href="{% url 'jobapp:jobseekerlogin' %}?next={{request.path}}">Login</a>
                </li>
                {% endif %}

            </ul>
        </div>
    </nav>
    {% block content %}

    {% endblock %}


    <script src="{% static 'jobseekerstatic/js/popper.min.js' %}"></script>
    <script src="{% static 'jobseekerstatic/js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'jobseekerstatic/js/bootstrap.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


    {% block js %}
    {% endblock %}
</body>

</html>

templates/jobseekertemplates/company.html
{% extends 'jobseekertemplates/base.html' %} {% block title %}All
Company{%endblock %} {% block content %}
<div class="container">
  <h3 class="mt-5 mb-5">All Companies</h3>
  {% for company in companies %}

  <div class="card mb-3" style="">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img
          src="{{company.company_image.url}}"
          class="card-img"
          alt="..."
          style="height: 250px; object-fit: contain"
        />
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <br>
          <h5 class="card-title">{{company.name}}</h5>
          <p><strong>Email: </strong>{{company.email}}</p>
          <p><strong>Address: </strong>{{company.address}}</p>
          <p><strong>Contact: </strong>{{company.mobile}}</p>
          <p><strong>Website: </strong>{{company.website}}</p>
        </div>
       
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<br />
{% endblock %}

templates/jobseekertemplates/jobseekerhome.html
{% extends 'jobseekertemplates/base.html' %}
{% block title %}Job Portal{% endblock %}
{% block css %}
{% endblock %}

{% block content %}

<main>
    <div class="container">
        <br><br>
        <h2>Search Available Job</h2>
        <form action="{% url 'jobapp:search' %} " method="GET" value="{{request.GET.search}}{{request.GET.location}}">
            <div class="form-row">
                <div class="col-md-4">
                    <input class="form-control" placeholder="Search Job by title,Category" aria-label="Search"
                        name="search">

                       
                </div>
                <div class="col-md-4">
                    <input class="form-control" placeholder="Location" aria-label="Search" name="location">
                </div>
                <button class="btn btn-success" type="submit" class="validate" name="submit"
                    value="Search">Search</button>
            </div>
        </form>
        <div>
            <button class="btn btn-warning"><a href="{% url 'jobapp:cv_builder' %}"> Build Resume</a></button>
        </div>

    </div>

    <div class="container mt-5 mb-5 pt-3">
        <table class="table table-hover">
            <h4>Recent Job Posts</h4>
            <thead>
                <tr>
                    <th scope="col">Job Title</th>
                    <th scope="col">Company Name</th>
                    <th scope="col">Skill</th>
                    <th scope="col">Location</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for job in jobs %}

                <tr class="table-active">
                    <td>{{job.title}}</td>
                    <td>{{job.employer.name}}</td>
                    <td>{{job.skills}}</td>
                    <td>{{job.employer.address}}</td>
                    <td>

                        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#{{job.id}}">
                            Details
                        </button>
                        <div class="modal fade" id="{{job.id}}" data-backdrop="static" data-keyboard="false"
                            tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="staticBackdropLabel">{{job.title}}
                                        </h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Company Name: <small>{{job.employer.name}}</small></p>
                                        <p>Address: <small>{{job.employer.address}}</small></p>
                                        <p>Salary: <small>{{job.salary}}</small></p>
                                        <p>Job Type: <small>{{job.job_type}}</small></p>
                                        <p style=" word-wrap: break-word;">Description: <small>{{job.details}}</small>
                                        </p>
                                        <p>Education: <small>{{job.education}}</small></p>
                                        <p>Career level: <small>{{job.level}}</small></p>
                                        <p>Experience: <small>{{job.experience}}</small></p>
                                        <p>Qualification; <small>{{job.employer.qualification}}</small></p>
                                        <p>Last Date to Apply: <small>{{job.deadline}}|</small></p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Close</button>

    
                                        <a href="{% url 'jobapp:jobseekerjobapply' job.id %}">Apply</a>
                                       
                                        
                                    </div>
                            
                                </div>
                            </div>
                        </div>

                    </td>

                </tr>
                {% endfor %}

            </tbody>
        </table>
        <div class="text-center">
            <button class="btn btn-primary center"><a href="{% url 'jobapp:alljob' %}">Load More Posts</a> </button>
        </div>
    </div>
    <br>

    <div class="container">
        <h3 class="text-center">Latest Job Opening Companies</h3> <br><br>
        <div class="row row-cols-1 row-cols-md-3">
            {% for employer in employers %}
            <div class="col mb-4 col-md-3">
                <div class="card h-100">
                    <img src="{{ employer.company_image.url}}" class="card-img-top"
                        style="height: 150px; object-fit: contain;" alt="...">
                    <div class="card-body">
                        <h6 class="card-title">{{ employer.name }}</h6>
                        <p class="card-text">Address: {{ employer.address }}</p>
                        <p class="card-text">Contact: {{ employer.mobile }}</p>
                        <p class="card-text">Website: {{ employer.website }}</p>
                    </div>
                    <div class="card-footer">
                        <!-- <small class="text-muted">Details</small> -->
                        
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <br><br>
</main>

{% endblock %}
{% block js %}
<script>
$('#age-min').change(function(){
    k=$('#age-min option:selected').text();
    alert(k);
})
</script>
{% endblock %}

templates/jobseekertemplates/jobseekerjobapply.html
{% extends 'jobseekertemplates/base.html' %}
{% load static %}
{% block content %}

{% if messages %}
<ul>
   {% for message in messages %}
	   <li>{{ message }}</li>
   {% endfor %}
</ul>
{% endif %}

<div class="container">
	<br><br>
	<div class="col-md-6">
		<h3>Provide your cover letter for job:</h3>
		<form method='post' enctype="multipart/form-data">
			{% csrf_token %}
			{{form.as_p }}
			<button class="btn btn-success">Apply</button>
		</form>
		
	</div>
</div>


{% endblock %}

templates/jobseekertemplates/jobseekerlogin.html
{% extends 'jobseekertemplates/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
{% if error %}
<li>{{error}}</li>
{% endif %}
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
		}

		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title {
			color: #fff;
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}

		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		.login_container {
			padding: 0 2rem;
		}

		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}

		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages {
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}

		a {
			color: inherit;
			text-decoration: none;
			text-align: center;
		}

		a:hover {
			color: #00A0C6;
			text-decoration: none;
			cursor: pointer;
		}
	</style>
</head>

<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">

					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" name="password" placeholder="Password..." class="form-control">
						</div>

						<div class="d-flex justify-content-center mt-3 login_container">
							<input class="btn login_btn" type="submit" value="Login">
						</div>
					</form>

				</div>

				<div class="">
					<div class=" justify-content-center links">
						Don't have an account? Create new account as
						<a href="{% url 'jobapp:jobseekerregistration' %}" class="ml-2">Job Seeker</a>
						<a href="{% url 'jobapp:employerregistration' %}" class="ml-2">Employer</a>
					</div>

				</div>
			</div>
		</div>
	</div>
</body>

</html>
{% endblock %}

templates/jobseekertemplates/jobseekerprofile.html
{% extends 'jobseekertemplates/base.html' %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endfor %}
{% endif %}
<div class="container">
    <p>Profile</p>
    <div class="card" style="width:400px">
      <img class="card-img-top" src="{{jobseeker.image.url}}" alt="Card image" style="width:100%">
      <div class="card-body">
        <h4 class="card-title">{{jobseeker.name}}</h4>
        <p class="card-text">{{jobseeker.about}}</p>
        <a href="{% url 'jobapp:jobseekerprofileupdate' jobseeker.id %}" class="btn btn-primary">UpdateProfile</a>
      </div>
    </div>
    <br>
   
{% comment %}
<!-- <a href="{% url 'jobapp:jobseekerpasswordchange' %}">ChangePassword</a> -->
{% endcomment %}
{% if jobseeker.jobapplication_set.all %}
<h3>Job I have Applied</h3>
</hr>

<table class='table table-bordered table-info'>
	<thead>
		<tr>
		<th>SN</th>
        <th>JobTitle</th>
        <th>Position</th>
        <th>Salary</th>
		<th>Company</th>
		<th>Date</th>
        <th>Skills</th>
        <th>is_appllied</th>
		</tr>
	</thead>
	<tbody>
		{% for jobapplication in jobseeker.jobapplication_set.all %}
	
		<tr>
			<td>{{forloop.counter}}</td>
            <td>{{jobapplication.job.title}}</td>
            <td>{{jobapplication.job.level}}</td>
            <td>{{jobapplication.job.salary}}</td>
			<td>{{jobapplication.job.employer.name}}</td>
            <td>{{jobapplication.created_at}}</td>
            <td>{{jobapplication.job.skills}}</td>
            <td>{{jobapplication.is_applied}}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endif %}
<hr>
{% if jobrecommend %}
<h2 style="text-align:center;" color="red;">Recommended job for you</h2>
<table class="table table-bordered table-info">
	<thead>
		<tr>
			<th>Job Positon</th>
				<th>Company</th>
                <th>Job Title</th>
                <th>Salary</th>
                <th>Deadline</th>
                <th>skills</th>
                <!-- <th>match value</th> -->
				<th>View Detail</th>

		</tr>
		
	</thead>
	<tbody>
            {% for job in jobrecommend %}
			<tr class="table-active">
                <td>{{job.level}}</td>
                <td>{{job.employer.name}}</td>
                <td>{{job.title}}</td>
                <td>{{job.salary}}</td>
                <td>{{job.deadline}}</td>
                <td>{{job.skills}}</td>
                <!-- <td>{{job.match_value}}</td> -->
                <td>

                       <button type="button" class="btn btn-info" data-toggle="modal" data-target="#{{job.id}}">
                        Details
                    </button>
                       <div class="modal fade" id="{{job.id}}" data-backdrop="static" data-keyboard="false"
                         tabindex="-1"
                         aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">{{job.title}}</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Company Name: <small>{{job.employer.name}}</small></p>
                                    <p>Address: <small>{{job.employer.address}}</small></p>
                                    <p>Salary: <small>{{job.salary}}</small></p>
                                    <p>Job Type: <small>{{job.job_type}}</small></p>
                                    <p>Description: <small>{{job.details}}small></p>
                                    <p>Education: <small>{{job.education}}</small></p>
                                    <p>Career level: <small>{{job.level}}</small></p>
                                    <p>Experience: <small>{{job.experience}}</small></p>
                                    <p>Qualification; <small>{{job.employer.qualification}}</small></p>
                                    <p>Last Date to Apply: <small>{{job.deadline}}|</small></p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                  
                                    <a href="{% url 'jobapp:jobseekerjobapply' job.id %}">Apply</a>
                                   
                                </div>
                            </div>
                        </div>
                    </div>
                
                </td>
            
            </tr>
            {% endfor %}
		
	</tbody>
		

</table>
{% endif %}

</div>



{% endblock %}

templates/jobseekertemplates/jobseekerregistration.html
{% extends 'jobseekertemplates/base.html' %}
{% block title %}Registration{% endblock %}

{% block content %}
{% for field in form %}
{% if field.errors %}

    <li class="alert alert-warning alert-dismissible fade show" role="alert">
      <strong>{{field.label}}</strong>&nbsp;{{field.errors|striptags}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button></li>
    {% endif %}

{% endfor %}
<div class="card">
  <div class="card-body">
<div class="container border">
  <h3 style="margin-left: 30%;">Registration Page for JobSeekers</h3>
  <form method="post" enctype="multipart/form-data" style="margin-left: 30%;">
    {% csrf_token %}
    {% for field in form %}
    
    <div class="form-group col-md-8">
      <label for="{{ field.id_for_label}}" class="label">{{ field.label }}</label>
      {{ field}}
      {% if field.help_text %}
    <span style="color: red;">{{field.help_text}}</span>
    {% endif %}
    </div>
    
    {% endfor %}
    <button type="submit" class="btn btn-primary">Register</button>
  </form>

  <div class="d-flex justify-content-center links">
    Already have an account? <a href="{% url 'jobapp:jobseekerlogin' %}" class="ml-2">Sign In</a>
  </div>
</div>
</div>
</div>

{% endblock %}

templates/jobseekertemplates/search.html
{% extends 'jobseekertemplates/base.html' %}
{% block title %}Search Results{% endblock %}
{% block css %}
{% endblock %}


{% block content %}
<div class="container">

    <h2>Search Available Job</h2>

    <form action="{% url 'jobapp:search' %} " method="GET">
        <div class="form-row">
            <div class="col-md-4">
                <input class="form-control" placeholder="Search Job by title,Category" aria-label="Search"
                    name="search">
            </div>
            <div class="col-md-4">
                <input class="form-control" placeholder="Location" aria-label="Search" name="location">
            </div>
            <button class="btn btn-success" type="submit" classs="validate" name="submit" value="Search">Search</button>
        </div>

    </form>

    {% if submits == 'Search' and request.GET.location == "" and request.GET.search == "" %}

    <div class="alert alert-success alert-dismissible fade show" role="alert">
        You can search jobs on the basis of <strong>Job Title and Location.</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>

    {% endif %}
    
    <br>
    <br>

    {% if submits == 'Search' and request.GET.search != "" %}
    {% for search in results %}

    <div class="card mb-3 shadow p-3 mb-5 bg-white rounded">
        <h5 class="card-header">{{search.title}}</h5>
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="{{search.image.url}}" style="margin-left: 25px; margin-top: 15px;" height="200" width="200">
            </div>
            <div class="col-md-9">
                <div class=" "></div>
                <h5 class="card-title"><i class="fas fa-building"
                        style="padding-right:15px;"></i>{{search.employer.name}}
                </h5>

                <p class="card-text"><i class="fas fa-map-marker-alt" style="padding-right:15px;"></i> Location:

                    {{search.employer.address}}</p>
                <p class="card-text"><i class="fas fa-clock" style="padding-right:15px;"></i>Job
                    Type:{{search.job_type}}
                </p>
                <p class="card-text"><i class="fas fa-brain"
                        style="padding-right:15px;"></i>Experience:{{search.experience}}
                </p>


                <p class="card-text"><i class="fas fa-money-check-alt" style="padding-right:15px;"></i>Salary:
                    {{search.salary}}
                </p>


                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#{{search.id}}">
                    Details
                </button>
                <div class="modal fade" id="{{search.id}}" data-backdrop="static" data-keyboard="false" tabindex="-1"
                    aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">{{search.title}}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Company Name: <small>{{search.employer.name}}</small></p>
                                <p>Address: <small>{{search.employer.address}}</small></p>
                                <p>Salary: <small>{{search.salary}}</small></p>
                                <p>Job Type: <small>{{search.job_type}}</small></p>
                                <p>Description: <small>{{search.details}}small></p>
                                <p>Education: <small>{{search.education}}</small></p>
                                <p>Career level: <small>{{search.level}}</small></p>
                                <p>Experience: <small>{{search.experience}}</small></p>
                                <p>Qualification; <small>{{search.employer.qualification}}</small></p>
                                <p>Last Date to Apply: <small>{{search.deadline}}|</small></p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <a href="{% url 'jobapp:jobseekerjobapply' search.id %}">Apply</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        {% empty %}
        <h1>result is not found</h1>
       <div> <a href="{% url 'jobapp:jobseekerhome' %}">Go to Home</a></div>

        {% endfor %}


        {% endif %}
    </div>
</div>
{% endblock %}